
title: Giu is unique
description: "Giu is unique-特立独行的Giu"
url: "http://liucanjiao.top"
author: Giu


author-image: /img/user.png

baseurl: "/"  # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


#color scheme
# sidebar-color: '#000'       #those apostrophes are important
# accent-color: '#F62459'     #those apostrophes are important
sidebar-color: '#3A539B'       
accent-color: '#3A539B' 

#social
#facebook: https://www.facebook.com/
#twitter: https://twitter.com/
#twitter-handle: '@sharathdt'     #for twitter button on author section #those apostrophes are important
github: https://github.com/
#youtube: https://www.youtube.com/channel/
#email: mailto:hello@webjeda.com
#feedburner-subscribe: https://feedburner.google.com/fb/a/mailverify?uri=webjedablog&amp;loc=en_US

#Other
#analytics: UA-71358787-1
#disqus-shortname: webjeda-sample    #Disqus comments
#google-custom-search-cx: '017575011755499056211:vwrwldvgq6s'        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.


# Get this from https://getsimpleform.com to make your contact form work as expected.
#simpleform-api-token:


destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
    style: compressed
    
gems: [jekyll-paginate]


